# Netlify configuration file

[build]
  publish = "public" # Ensure this matches your static file directory
  command = "" # No build command since this is an EJS app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://dashboard-cg29.onrender.com/api/:splat"
  status = 200
  force = true
